Why Loops Are Slow

In [2]:
# Example -- Looping Over Arrays in Python
import numpy as np 
arr = np.array([1,2,3,4,5,6])
result = []

# using a loop to square each element 
for num in arr:
    result.append(num ** 2)

print(result)

[np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25), np.int64(36)]


But what if i say we have other option than this and that will make the executionability of the code more faster as compared to this 

In [5]:
arr = np.array([1,2,3,4,5,6])
result = arr ** 2
print(result)

[ 1  4  9 16 25 36]


In [6]:
result

array([ 1,  4,  9, 16, 25, 36])

In [8]:
arr = np.array([1,2,3,4,5,6])
result = arr + 10
print(result)

[11 12 13 14 15 16]


# Broadcasting with arrays of Diffrent Shapes

In [9]:
# Broadcasting with two 1d arrays 
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,0,1,2])
result = arr1 + arr2. # This is a broadcasting called ELement-wise addition
print(result)

[ 8 10 12  4  6  8]


In [11]:
# Numpy automatically aligns the two arrays and performs element wise addition,
arr1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
arr2 = np.array([1,2,3,4,5])
result = arr1 + arr2
print(result)

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


# Normalinzing data using broadcasting 
if i say how can we get normalization in broadcasting then the ans 
we will subtract mean from the data and divide buy std deviation 
data-mean/std

In [12]:
data  = np.array([[10,20,30],[40,50,60],[70,80,90]])

# Calculating mean and standar deviation 
mean = data.mean(axis=0)
std = data.std(axis=0)

normalized_data = (data-mean)/std
print(normalized_data)

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
