In [16]:
import numpy as np
arr = np.array([10,46,87,89])
np.mean(arr)



np.float64(58.0)

arr.dtype


In [18]:
np.mean(arr)

np.float64(58.0)

np.std() -- Compute the standard deviation of an array

In [19]:
np.std(arr)

np.float64(32.59601202601324)

np.var() -- compute the variance of an array


In [20]:
np.var(arr)

np.float64(1062.5)

In [23]:
arr.var()

np.float64(1062.5)

np.min -- Compute the minimum value of the array


In [24]:
arr.min()

np.int64(10)

In [25]:
np.min(arr)

np.int64(10)

np.max -- Compute the maximum value of an array 

np.sum -- compute the sum of all elements of an array

In [26]:
arr.sum()

np.int64(232)

In [27]:
np.sum(arr)

np.int64(232)

np.prod() -- compute all the product of an array

In [28]:
arr.prod()

np.int64(3561780)

In [29]:
np.prod(arr)

np.int64(3561780)

np.median -- Computing the median of an array 

In [31]:
np.median(arr)

np.float64(66.5)

In [36]:
np.median(arr)

np.float64(66.5)

np.percentile() -- calculate the percentile of an array

In [40]:
np.percentile(arr,100)

np.float64(89.0)

np.argmin() -- Return the index of the minimum value in an array

In [43]:
np.argmin(arr)

np.int64(0)

In [44]:
np.argmax(arr)

np.int64(3)

np.corrcoef(arr1,arr2) - compute the correlation coefficient matrix of two arrays 

In [46]:
arr1 = np.array([1,2,3])

In [47]:
arr2 = np.array([1,2,4])

In [48]:
np.corrcoef(arr1,arr2)

array([[1.        , 0.98198051],
       [0.98198051, 1.        ]])

np.unique() -- Find the unique element of an array

In [49]:
np.unique(arr)

array([10, 46, 87, 89])

np.diff() -- conmpute the n-th difference of an array

In [50]:
np.diff(arr)

array([36, 41,  2])

np.cumsum() -- compete the cumulative sum of an array

In [51]:
np.cumsum(arr)

array([ 10,  56, 143, 232])

np.linspace() -- Create an array with evenly spaced numbers over a specified interval

In [54]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

nyp.log() -- compute the natural algorithm of an arra

In [55]:
np.log(arr)

array([2.30258509, 3.8286414 , 4.46590812, 4.48863637])

np.exp() -- compute the exponential of an array

In [57]:
np.exp(arr)

array([2.20264658e+04, 9.49611942e+19, 6.07603023e+37, 4.48961282e+38])