In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])

In [4]:
print(arr1)


[1 2 3 4 5 6 7 8 9]


In [5]:
arr2 = np.array([[10,20,30],[30,40,50]])

In [6]:
print(arr2)


[[10 20 30]
 [30 40 50]]


# Creating Array from scratch:

In [7]:
# any matrix like 3 * 3 matrix fill with zeros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
# If i need matrix full of ones 
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# like we can do mor than ones as above if i need the matix fill with 2 3 4 5 6 thn what we ned to 
np.full((2,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [14]:
np.full((4,5),9)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [17]:
# like if i say i want a identity matrix 
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [22]:
# like as i solve the exercise questions if i say i want to print all the range or all th array between 10 to 100
np.arange(1000,2000,50)

array([1000, 1050, 1100, 1150, 1200, 1250, 1300, 1350, 1400, 1450, 1500,
       1550, 1600, 1650, 1700, 1750, 1800, 1850, 1900, 1950])

In [24]:
# if i talk about linespace basically linespace represent how much number is possible within the given range but the thing is that you need to keep equal distance or equal portion 
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
# key takeway  that i got is that: Numpy offer powerful shortcuts to create array without loops!

# Checking Array Operators 

In [31]:
arr = np.array([[10,20,30],[40,50,60]])

print("Shape: ", arr.shape)
print("Size: ", arr.size)
print("Dimensions: ", arr.ndim)
print("Data type: ", arr.dtype)

Shape:  (2, 3)
Size:  6
Dimensions:  2
Data type:  int64


Numpy arrays are strongly typed, meaning all elements share the same data type.

# Changing Data Types

In [32]:
arr = np.array([[10,20,30],[40,50,60]], dtype = "float32")

In [33]:
arr.dtype

dtype('float32')

In [34]:
n = arr.astype("float64")


n.dtype

In [36]:
arr.dtype

dtype('float32')

Efficient memory usage by choosing the right data type

In [39]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr.shape)

(2, 3)


In [43]:
myarr = arr.reshape(3,2)

In [45]:
myarr

array([[10, 20],
       [30, 40],
       [50, 60]])

In [46]:
myarr.flatten()

array([10, 20, 30, 40, 50, 60])

# Indexing and slicing 

In [47]:
# INdexing 
arr = np.array([10,20,30,40])
print(arr[0])


10


In [48]:
print(arr[1])

20


In [53]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr[1])

[40 50 60]


In [55]:
print(arr[1][1])

50


In [56]:
arr = np.array([10,20,30,40,50,60])

print(arr[1:4])

[20 30 40]


In [57]:
print(arr[0:4])

[10 20 30 40]


In [58]:
print(arr[:4])


[10 20 30 40]


In [59]:
print(arr[4:])

[50 60]


In [61]:
print(arr[::2]) # this represent the difference actually 

[10 30 50]


In [62]:
arr

array([10, 20, 30, 40, 50, 60])

In [63]:
b = arr[3:7]

In [64]:
print(b)


[40 50 60]


In [65]:
b[0] = 444444

In [66]:
b


array([444444,     50,     60])

In [67]:
arr

array([    10,     20,     30, 444444,     50,     60])

so changes in the slice affect the original array

but if we are using .copy() function  then it is not going to change in the actual arraya 

# Fancy indexing(Select multiple elements 

In [68]:
arr = np.array([10,20,30,40,50])
idx = [0,2,3]
print(arr[idx])

[10 30 40]


# Boolean Masking

In [70]:
arr = np.array([10,20,30,40,50,60,70])
mask = arr > 25
print(arr[mask]) # This is a powerful tool that is used to filter large dataset efficiently

[30 40 50 60 70]
