In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr.dtype)

int64


Changing data type

# You can cast(convert) the data type of an array using the .astype() method. THis is useful when you need to change the type for a specific operation or when you want to reduce memeory usage.

In [3]:
# Changine Data Types
arr = np.array([1,2,3,4,5,6,7,8,9])

In [4]:
print(arr.dtype)

int64


In [5]:
arr.astype("int32")

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [6]:
arr.dtype

dtype('int64')

In [13]:
arr_int = arr.astype(np.int32)

In [14]:
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr.dtype

dtype('int64')

In [16]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#### Doing downcasting to save the memory

In [18]:
arr_large = np.array([100000, 2000000, 3000000], dtype = np.int64)

In [19]:
arr_large.dtype

dtype('int64')

In [20]:
arr_small = arr_large.astype(np.int32) # This is basicallly a downcasting to a samller type 

In [21]:
arr_small.dtype

dtype('int32')

In [22]:
print(arr_small)

[ 100000 2000000 3000000]


In [23]:
print(arr_small.dtype)

int32


# Why Data Types Matter in Numpy

In [24]:
arr_int64 = np.array([1,2,3], dtype=np.int64)

In [25]:
arr_int32 = np.array([6,7,8], dtype=np.int32)

In [26]:
print(arr_int32.nbytes)
print(arr_int64.nbytes)

12
24


# String Data Type in Numpy

In [27]:
arr = np.array(["Apple","Banana","Cat","Dog","Elephant","Fish"],dtype='U10')

In [28]:
arr

array(['Apple', 'Banana', 'Cat', 'Dog', 'Elephant', 'Fish'], dtype='<U10')

In [30]:
arr.dtype

dtype('<U10')

Complex Numbers

In [32]:
arr = np.array([1+2j, 2+3j,4+5j],dtype=np.complex128)

In [33]:
arr

array([1.+2.j, 2.+3.j, 4.+5.j])

In [34]:
arr = np.array([1+2j, 2+3j,4+5j],dtype="complex128") # Here we can use complez 64 too in place of complex 128

In [35]:
arr

array([1.+2.j, 2.+3.j, 4.+5.j])

# Object Data Types


In [36]:
arr = np.array([{'a':1},"Rohit",8],dtype="object")

In [37]:
arr.dtype

dtype('O')

In [38]:
arr

array([{'a': 1}, 'Rohit', 8], dtype=object)