Create a 3 * 3 array filled with random numbers and print its shape 

In [7]:
import numpy as np

In [8]:
arr

array([[[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

In [9]:
arr.shape

(1, 3, 3)

In [11]:
myarr = np.random.randint(1,100, size = (3,3))


In [12]:
myarr

array([[42, 34, 82],
       [54,  2, 28],
       [90, 27, 75]])

Convert  an array of floats [1.1, 2.2, 3.3] into integers

In [13]:
arr1 = np.array([1.1,2.2,3.3])


In [14]:
arr1.astype("int32")

array([1, 2, 3], dtype=int32)

Use fancy  indexing to extract even numbers from [1,2,3,4,5,6]

In [22]:
arr1 = np.array([1,2,3,4,5,6])
idx = [1,3,5]
print(arr1[idx])

[2 4 6]


Reshape a 1D array of size 9 into a 3 * 3 matrix

In [25]:
myarr = np.array([1,2,3,4,5,6,7,8,9])
print(myarr)
myarr.shape
myarr.reshape(3,3)


[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Use boolean masking to filter numbers greater than 50 in an array

In [32]:
myarr = np.arange(1,100)

In [33]:
myarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [34]:
mask = myarr > 50

In [35]:
print(myarr[mask])

[51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
 99]
