In [1]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
arr[0]

array([1, 2, 3])

In [6]:
arr[1]

array([4, 5, 6])

In [7]:
arr[2]

array([7, 8, 9])

 # axis 0(rows) -- operation move down the columns
 # axis 1(columns) -- operation move across the rows

In [10]:
np.sum(arr, axis=0) # Sum along rows (down each column) 

array([12, 15, 18])

In [11]:
np.sum(arr, axis=1)  # Sum along column (across each row)

array([ 6, 15, 24])


Indexing in MUltidimensional Arrays

In [12]:
arr[0][1]

np.int64(2)

In [13]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr[0][1]

np.int64(2)

In [15]:
arr[0:1]

array([[1, 2, 3]])

In [16]:
arr[0,1] # zeroth rown and column i lelo 

np.int64(2)

In [17]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

# Indexing in 3D Arrays

For 3D arrays, the first index refers to the "depth" (sheets of data).

In [18]:
arr3D = np.array([[[1,2,3], [4,5,6]],[[7,8,9], [10,11,12]]])

In [22]:
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
arr3D.shape

(2, 2, 3)

Accessing elements in 3D

In [24]:
#First sheet, second row, third columna
arr[0,1,2]

np.int64(60)

In [25]:
arr3D[:, 0, :]

array([[1, 2, 3],
       [7, 8, 9]])

Practical Example: Selecting Data Along Axes

In [29]:
# Get all rows of the first column 
arr = np.array([[[1,1,1],[1,2,3]],
                [[4,4,4],[5,5,5]]])

In [30]:
first_col = arr[:,0]

In [31]:
first_col

array([[1, 1, 1],
       [4, 4, 4]])

In [32]:
# Get the first row from each "sheet" in a 3D array

In [33]:
first_rows = arr3D[:, 0, :]

In [34]:
print(first_rows)

[[1 2 3]
 [7 8 9]]


Changing Data Along an Axis

In [38]:
# Replace all elements in column 1 with 0
arr3D[:, 1] = 0

In [39]:
print(arr3D)

[[[1 2 3]
  [0 0 0]]

 [[7 8 9]
  [0 0 0]]]
